spring.application.name=spring-ai-agent-demo
spring.ai.bedrock.aws.region=us-east-1
spring.ai.bedrock.aws.timeout=10m
spring.ai.bedrock.converse.chat.options.max-tokens=100
spring.ai.bedrock.converse.chat.options.model=amazon.nova-lite-v1:0
cognito.user.pool.name=sample-agentcore-gateway-pool
cognito.user.pool.client.name=sample-agentcore-gateway-client
cognito.auth.token.resource.server.id=sample-agentcore-gateway-id
#amazon.bedrock.agentcore.gateway.url=https://demoamazonapigatewayordersrestapinew-4xvdheq7um.gateway.bedrock-agentcore.us-east-1.amazonaws.com/mcp
amazon.bedrock.agentcore.gateway.base.url=https://demoamazonapigatewayordersrestapinew-4xvdheq7um.gateway.bedrock-agentcore.us-east-1.amazonaws.com
amazon.bedrock.agentcore.gateway.endpoint=/mcp

#agentcore.memory.sessionId=12345
#agentcore.memory.actor=user_actor

# short-term memory
#agentcore.memory.memory-id=OrderStatisticsAgentMemory-HrBN7mDutn
agentcore.memory.total-events-limit=10
agentcore.memory.default-session=default-session-id-12345678
agentcore.memory.page-size=50
agentcore.memory.ignore-unknown-roles=true

# long-term memory
agentcore.memory.memory-id=OrderStatisticsAgentMemoryWithStrategies-KbblGpGPKj


#auto-discovery long term memory strategies
agentcore.memory.long-term.auto-discovery=true
#agentcore.memory.long-term.semantic.strategy-id=CustomerSupportSemantic-AX61aX38ZR
#agentcore.memory.long-term.semantic.top-k=7
#agentcore.memory.long-term.scope=ACTOR 
#agentcore.memory.long-term.semantic.namespace-pattern=support/customer/{actorId}/semantic
   
#agentcore.memory.long-term.summary.strategy-id=CustomerSummary-ic9C4aAGIt
#agentcore.memory.long-term.summary.top-k=7
#agentcore.memory.long-term.scope=SESSION 
#agentcore.memory.long-term.summary.namespace-pattern=support/customer/{actorId}/{sessionId}/summary

logging.level.org.springaicommunity.agentcore.memory=DEBUG 
agentcore.throttle.invocations-limit=20
agentcore.throttle.ping-limit=250