embabel.models.default-llm=us.anthropic.claude-sonnet-4-6
embabel.models.llms.best=us.anthropic.claude-sonnet-4-6
#embabel.models.llms.best=us.amazon.nova-pro-v1:0
embabel.models.llms.balanced=us.amazon.nova-pro-v1:0

conference.attendee.llm.role=best
conference.attendee.persona.role=Conference attendee
conference.attendee.persona.goal=Conduct thorough conferences search with the information (topics, conference dates) provided so I decide which to attend.
conference.attendee.persona.backstory=As a Conference Attendee Specialist, your mission is to find the suitable conference which match the given request


conference.speaker.llm.role=best
conference.speaker.persona.role=Conference speaker
conference.speaker.persona.goal=Conduct the search for the talks or create the talk with the given criteria with the conference application for those talks
conference.speaker.persona.backstory=As a Conference Speaker Specialist, your mission is to search for the talk or create the talk with the given criteria with the conference application for those talks

               
#embabel.agent.logging.personality=starwars
embabel.agent.platform.llm-operations.data-binding.max-attempts=1
embabel.agent.platform.ranking.max-attempts=1

spring.application.name=embabel-conference-search-demo
spring.ai.bedrock.aws.region=us-east-1
spring.ai.bedrock.aws.timeout=10m
spring.ai.bedrock.converse.chat.options.max-tokens=1000
spring.ai.mcp.client.type=SYNC


cognito.user.pool.name=UserPoolForAgentCoreMCP
cognito.user.pool.client.name=UserPoolClientWithUserAndPasswordForAgentCoreMCP
cognito.auth.token.resource.server.id=AgentCoreResourceServerId


# configure if if you use MCP through AgentCore Gateway, otherwise leave the value empty
# Don't delete property itself
amazon.bedrock.agentcore.gateway.url=https://spring-ai-conference-search-agentcore-gateway-xizwpytsgm.gateway.bedrock-agentcore.us-east-1.amazonaws.com/mcp

# configure the runtime.id, aws region and account id if you use MCP through AgentCore Runtime MCP Server,
# otherwise leave all 3 values empty. Don't delete properties themselves
# If both agentcore.runtime.id and amazon.bedrock.agentcore.gateway.url are defined, the first the takes precedence
#amazon.bedrock.agentcore.runtime.id=spring_ai_conference_search_agentcore_runtime-6dnMIL9i65
amazon.bedrock.agentcore.runtime.id=
aws.region=us-east-1

logging.level.root=INFO
logging.level.org.springframework.ai.mcp=DEBUG
logging.level.io.modelcontextprotocol.client=DEBUG
logging.level.io.modelcontextprotocol.client.transport=DEBUG
logging.level.io.modelcontextprotocol.spec=DEBUG
logging.level.org.springframework.web.reactive.function.client=DEBUG