spring.application.name=spring-ai-conference-search-demo
spring.ai.bedrock.aws.region=us-east-1
spring.ai.bedrock.aws.timeout=10m
spring.ai.bedrock.converse.chat.options.max-tokens=100
spring.ai.bedrock.converse.chat.options.model=amazon.nova-lite-v1:0
cognito.user.pool.name=MyUserPool
cognito.user.pool.client.name=MyClient
secrets.manager.secret.name={$YOUR_SECRET_MANAGER_SECRET_NAME}
spring.ai.mcp.client.type=ASYNC
amazon.bedrock.agentcore.runtime.id={$YOUR_AGENTCORE_RUNTIME_ID}
aws.account.id={$YOUR_AWS_ACCOUNT_ID}
aws.region=us-east-1

logging.level.root=INFO
logging.level.org.springframework.ai.mcp=DEBUG
logging.level.io.modelcontextprotocol.client=DEBUG
logging.level.io.modelcontextprotocol.client.transport=DEBUG
logging.level.io.modelcontextprotocol.spec=DEBUG
logging.level.org.springframework.web.reactive.function.client=DEBUG

