spring.ai.mcp.server.type=SYNC
#spring.ai.mcp.server.protocol=STREAMABLE
spring.ai.mcp.server.protocol=STATELESS
#spring.ai.mcp.server.stateless.disallow-delete=true


server.port=8000
server.address=0.0.0.0

logging.level.root=INFO
logging.level.org.springframework.ai.mcp=DEBUG