spring.application.name=spring-ai-conference-search-and-application-agent-bedrock-agentcore-runtime
spring.ai.bedrock.aws.timeout=10m
spring.ai.bedrock.converse.chat.options.max-tokens=100
spring.ai.bedrock.converse.chat.options.model=amazon.nova-lite-v1:0


cognito.user.pool.name=UserPoolForAgentCoreMCP
cognito.user.pool.client.name=UserPoolClientWithUserAndPasswordForAgentCoreMCP
cognito.auth.token.resource.server.id=AgentCoreResourceServerId

spring.ai.mcp.client.type=ASYNC


# configure if if you use MCP through AgentCore Gateway, otherwise leave the value empty
# Don't delete property itself
amazon.bedrock.agentcore.gateway.base.url=https://spring-ai-conference-search-agentcore-gateway-xizwpytsgm.gateway.bedrock-agentcore.us-east-1.amazonaws.com
amazon.bedrock.agentcore.gateway.endpoint=/mcp

# configure the runtime.id, aws region and account id if you use MCP through AgentCore Runtime MCP Server,
# otherwise leave all 3 values empty. Don't delete properties themselves
# If both agentcore.runtime.id and amazon.bedrock.agentcore.gateway.url are defined, the first the takes precedence
#amazon.bedrock.agentcore.runtime.id=spring_ai_conference_search_agentcore_runtime-6dnMIL9i65
amazon.bedrock.agentcore.runtime.id=
aws.region=us-east-1


# short-term memory
agentcore.memory.memory-id=short_term_memory_for_conference_application-67xrud6KNM
agentcore.memory.total-events-limit=10
agentcore.memory.default-session=default-session-id-12345678
agentcore.memory.page-size=50
agentcore.memory.ignore-unknown-roles=true

# long-term memory
#agentcore.memory.memory-id=long_term_memory_for_conference_application-K2Vg4aGfOo
#auto-discovery long term memory strategies
#agentcore.memory.long-term.auto-discovery=true


logging.level.root=INFO
logging.level.org.springframework.ai.mcp=DEBUG
logging.level.io.modelcontextprotocol.client=DEBUG
logging.level.io.modelcontextprotocol.client.transport=DEBUG
logging.level.io.modelcontextprotocol.spec=DEBUG
logging.level.org.springframework.web.reactive.function.client=DEBUG

agentcore.throttle.invocations-limit=20
agentcore.throttle.ping-limit=250

